version: 2.1

jobs:
  build:
    docker:
      - image: docker.io/cirrusci/flutter:latest

    steps:
      - checkout

      - run:
          name: Flutter Pub Get
          command: flutter pub get

      # Add more steps for testing, building, or other tasks as needed

workflows:
  version: 2
  build:
    jobs:
      - build
