version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout

      - run:
          name: Install Flutter dependencies
          command: flutter pub get

      # - run:
      #     name: Run Flutter tests
      #     command: flutter test

      # # Add additional steps for building and deploying as needed
