version: 2.1

orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node

    steps:
      - checkout

      - flutter/install: # Install Flutter using the orb
          version: 2.8.0 # Replace with the desired Flutter version

      - run:
          name: Flutter Version Check
          command: flutter --version

      - run:
          name: Flutter Pub Get
          command: flutter pub get  
      

