version: 2.1

orbs:
  flutter: circleci/flutter@2.0.2

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node

    steps:
      - checkout

      - flutter/install

      - run:
          name: Check Flutter Version
          command: flutter --version 
      

