version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/cirruslabs/flutter:latest
    steps:
      - checkout

      - run: 
          name: Get flutter doctor
          command: flutter doctor

      - run:
          name: Get flutter dependencies
          command: flutter pub get

      - run:
          name: "create signing key for android"
          command: |
            echo $RELEASE_KEYSTORE_FILE | base64 -d > android/app/key.jks
            echo "storeFile=../app/key.jks" > android/key.properties
            echo "storePassword=$RELEASE_KEYSTORE_PASSWORD" >> android/key.properties
            echo "keyAlias=$RELEASE_KEYSTORE_ALIAS" >> android/key.properties
            echo "keyPassword=$RELEASE_KEYSTORE_KEY_PASSWORD" >> android/key.properties

      - run: 
          name: Build the apk file
          command: flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: main