version: 2.1

orbs:
  flutter: circleci/flutter@2.0.0

jobs:
  build_ios:
    macos:
      xcode: 15.0.0 
    
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.16.1
      
      - flutter/install_ios_pod
      - flutter/install_ios_gem

      - run:
          command: flutter doctor
  