# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.1'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor    

      - name: Install dependencies
        run: flutter pub get

      - name: Compile for android
        run: flutter build apk --debug --split-per-abi

      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          tag: v0.0.0
          replacesArtifacts: false
          allowUpdates: true
          token: "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"




